---

application:
  client-origin-url: ${CLIENT_ORIGIN_URL}
  auth0:
      domain: ${OKTA_OAUTH_MGMT_DOMAIN}
      client:
        id: ${OKTA_OAUTH_MGMT_CLIENT_ID}
        secret: ${OKTA_OAUTH_MGMT_CLIENT_SECRET}
      audience: ${OKTA_OAUTH_MGMT_AUDIENCE}


server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hibernate.format_sql: true
        use-new-id-generator-mappings: false
    show-sql: false
    open-in-view: false

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    com.wheelerkode.library: TRACE

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}
...
